### ISSUE TITLE
Minor improvement to Pipeline Designer: Disable Text-Selection

### ISSUE THREAD

**Issue by BeniGemperle** [2sic/2sxc#992]
When I want to rename a stream i have to double-click it's name. But this does also select all text on that web-page which doesn't look nice and is an unexpected behavior in this case.

With CSS the text-selection could be easily disabled:

``` CSS
.noselect {
    cursor: default;
    -webkit-touch-callout: none;
    -webkit-user-select: none;
    -khtml-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
    user-select: none;
}
```

(see http://stackoverflow.com/a/32299832/4049371)
